--
-- PostgreSQL database dump
--

\restrict 8tGRZMStnfHAqP9M3naZeX3KxszfgbaEN68anU3Yom4j1aqZdWOX280H8MEdmce

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-19 16:33:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16406)
-- Name: ask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ask (
    id integer NOT NULL,
    username character varying(22) NOT NULL,
    question text CONSTRAINT ask_pertanyaan_not_null NOT NULL,
    answer text DEFAULT 'kosong'::text CONSTRAINT ask_jawaban_not_null NOT NULL
);


ALTER TABLE public.ask OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16436)
-- Name: ask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16391)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(16) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(11) DEFAULT 'user'::character varying NOT NULL,
    number_phone character varying(16) DEFAULT 'kosong'::character varying CONSTRAINT users_telepon_not_null NOT NULL,
    hobby character varying(16) DEFAULT 'kosong'::character varying CONSTRAINT users_hobi_not_null NOT NULL,
    last_login time without time zone
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16425)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5018 (class 0 OID 16406)
-- Dependencies: 220
-- Data for Name: ask; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ask (id, username, question, answer) FROM stdin;
2	dymarr		belum dijawab
6	dymarr	dammar mana	belum dijawab
\.


--
-- TOC entry 5017 (class 0 OID 16391)
-- Dependencies: 219
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password, role, number_phone, hobby, last_login) FROM stdin;
5	dymarr	$2b$12$6Tthw7dB1PX1rZp45D8nV.S6sgq5AZKKD8AMl55GrGPjdj.HEgBsy	user	kosong	kosong	18:36:16.184659
\.


--
-- TOC entry 5026 (class 0 OID 0)
-- Dependencies: 222
-- Name: ask_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ask_id_seq', 6, true);


--
-- TOC entry 5027 (class 0 OID 0)
-- Dependencies: 221
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- TOC entry 4868 (class 2606 OID 16417)
-- Name: ask ask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ask
    ADD CONSTRAINT ask_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 16404)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 5016 (class 6104 OID 16424)
-- Name: dymarr; Type: PUBLICATION; Schema: -; Owner: postgres
--

CREATE PUBLICATION dymarr FOR ALL TABLES WITH (publish = 'insert, update, delete, truncate');


ALTER PUBLICATION dymarr OWNER TO postgres;

-- Completed on 2026-04-19 16:33:28

--
-- PostgreSQL database dump complete
--

\unrestrict 8tGRZMStnfHAqP9M3naZeX3KxszfgbaEN68anU3Yom4j1aqZdWOX280H8MEdmce

